"""initial postgres schema

Revision ID: 740ba2720f23
Revises: edcdc807331e
Create Date: 2025-12-13 02:41:42.723698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '740ba2720f23'
down_revision: Union[str, Sequence[str], None] = 'edcdc807331e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_alerta', sa.String(length=50), nullable=True),
    sa.Column('porcentaje_defectos', sa.Float(), nullable=True),
    sa.Column('total_inspecciones', sa.Integer(), nullable=True),
    sa.Column('total_rechazados', sa.Integer(), nullable=True),
    sa.Column('umbral_configurado', sa.Float(), nullable=True),
    sa.Column('recomendacion', sa.Text(), nullable=True),
    sa.Column('notificacion_enviada', sa.Boolean(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alertas_id'), 'alertas', ['id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=True),
    sa.Column('contacto', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_nombre'), 'clientes', ['nombre'], unique=True)
    op.create_table('reportes_semanales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('total_inspecciones', sa.Integer(), nullable=True),
    sa.Column('total_rechazados', sa.Integer(), nullable=True),
    sa.Column('total_aprobados', sa.Integer(), nullable=True),
    sa.Column('porcentaje_defectos', sa.Float(), nullable=True),
    sa.Column('tendencia', sa.Float(), nullable=True),
    sa.Column('generado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reportes_semanales_id'), 'reportes_semanales', ['id'], unique=False)
    op.create_table('lotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_lote', sa.String(length=30), nullable=True),
    sa.Column('inspector', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lotes_codigo_lote'), 'lotes', ['codigo_lote'], unique=True)
    op.create_index(op.f('ix_lotes_id'), 'lotes', ['id'], unique=False)
    op.create_table('inspecciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resultado', sa.String(length=20), nullable=True),
    sa.Column('max_distancia', sa.Float(), nullable=True),
    sa.Column('puntos_defectuosos', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspecciones_categoria'), 'inspecciones', ['categoria'], unique=False)
    op.create_index(op.f('ix_inspecciones_id'), 'inspecciones', ['id'], unique=False)
    op.create_table('validaciones_lote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=False),
    sa.Column('accion', sa.String(length=20), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_aprobados', sa.Integer(), nullable=True),
    sa.Column('total_rechazados', sa.Integer(), nullable=True),
    sa.Column('total_pendientes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validaciones_lote_id'), 'validaciones_lote', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validaciones_lote_id'), table_name='validaciones_lote')
    op.drop_table('validaciones_lote')
    op.drop_index(op.f('ix_inspecciones_id'), table_name='inspecciones')
    op.drop_index(op.f('ix_inspecciones_categoria'), table_name='inspecciones')
    op.drop_table('inspecciones')
    op.drop_index(op.f('ix_lotes_id'), table_name='lotes')
    op.drop_index(op.f('ix_lotes_codigo_lote'), table_name='lotes')
    op.drop_table('lotes')
    op.drop_index(op.f('ix_reportes_semanales_id'), table_name='reportes_semanales')
    op.drop_table('reportes_semanales')
    op.drop_index(op.f('ix_clientes_nombre'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_alertas_id'), table_name='alertas')
    op.drop_table('alertas')
    # ### end Alembic commands ###
